### ISSUE TITLE
Spoor Landing Page

### ISSUE THREAD

**Issue by frknasir** [CJIDNG/POD#4]
Work needs to be done on spoor Landing page to make it more presentable.

- [ ] Meeting with @AMG63-Bassim (Bassim can start writing what he needs here with screenshots and what not)

**Comment by AMG63-Bassim** [comment]
I have looked at the look at the landing page and I do not think it fits what spoor stands for. Spoor is a not news platform. I have had a few conversations with Faruk. For instance, the red background and iMac shouldn't be there.
<img width="635" alt="Screenshot 2020-05-28 at 15 47 16" src="https://user-images.githubusercontent.com/60357404/83156903-e3a91a80-a0fa-11ea-8efc-d7a65f720ec0.png">

**Comment by AMG63-Bassim** [comment]
"Data" button should be changed to "Resources"

**Comment by AMG63-Bassim** [comment]
Can the "login" disappear for the general public?

**Comment by AMG63-Bassim** [comment]
Even though the platform is not a news platform, I still think the platform should have a featured article/latest post. This picture portrays somewhat what I mean 
<img width="1149" alt="Screenshot 2020-05-28 at 16 51 59" src="https://user-images.githubusercontent.com/60357404/83164018-a1380b80-a103-11ea-86e5-afed917ea09b.png">

**Comment by AMG63-Bassim** [comment]
Is the logo itself going up there instead of just "SpoorAfrica"?

**Comment by AMG63-Bassim** [comment]
How close are we to achieving the social media share button? and also the mail chimp thing we spoke about @frknasir

**Comment by AMG63-Bassim** [comment]
As discusses @frknasir 
Replace: 
- "Data" with "Resources"
- Header with Featured Article and scrap the redish background and the iMac
- "What we do" is not necessary, it should also be scrapped, it affects the obstructs the three articles at the bottom of the page
- Is "platforms" at the bottom of the page necessary?
-

**Comment by OdunayoOkebunmi** [comment]
> I have looked at the look at the landing page and I do not think it fits what spoor stands for. Spoor is a not news platform. I have had a few conversations with Faruk. For instance, the red background and iMac shouldn't be there.
> <img alt="Screenshot 2020-05-28 at 15 47 16" width="635" src="https://user-images.githubusercontent.com/60357404/83156903-e3a91a80-a0fa-11ea-8efc-d7a65f720ec0.png">

@AMG63-Bassim, do you have a design in mind or a site to reference?
